create database health;
use health;
create table covid(
  iso_code varchar(50),
  continent varchar(50),
  location varchar(50),
  date_of_addmission datetime,
  total_cases int,
  new_cases int,
  new_cases_smoothed float,
  total_deaths float,
  new_deaths int,
  new_deaths_smoothed float,
  total_cases_per_million float,
  new_cases_per_million float,
  new_cases_smoothed_per_million float,
  total_deaths_per_million float,
  new_deaths_per_million float,
  new_deaths_smoothed_per_million float,
  reproduction_rate float,
  icu_patients int,
  icu_patients_per_million float,
  hosp_patients int,
  hosp_patients_per_million float,
  weekly_icu_admissions int,
  weekly_icu_admissions_per_million float,
  weekly_hosp_admissions float,
  weekly_hosp_admissions_per_million float,
  total_tests int,
  new_tests int,
  total_tests_per_thousand float,
  new_tests_per_thousand float,
  new_tests_smoothed int,
  new_tests_smoothed_per_thousand float,
  positive_rate float,
  tests_per_case float,
  tests_units varchar(50),
  total_vaccinations int,
  people_vaccinated int,
  people_fully_vaccinated int,
  total_boosters int,
  new_vaccinations int,
  new_vaccinations_smoothed int,
  total_vaccinations_per_hundred float,
  people_vaccinated_per_hundred float,
  people_fully_vaccinated_per_hundred float,
  total_boosters_per_hundred int,
  new_vaccinations_smoothed_per_million int,
  new_people_vaccinated_smoothe float,
  stringency_index	float,
  population int,
  population_density float,	
  median_age float,	
  aged_65_older	float,
  aged_70_older	float,
  gdp_per_capita float,	
  extreme_poverty float,	
  cardiovasc_death_rate	float,
  diabetes_prevalence float,	
  female_smokers float, 	
  male_smokers float,	
  handwashing_facilities float,	
  hospital_beds_per_thousand float,	
  life_expectancy float,	
  human_development_index float,	
  excess_mortality_cumulative_absolute float,	
  excess_mortality_cumulative float,	
  excess_mortality	float,
  excess_mortality_cumulative_per_million float);
  
  
 LOAD DATA LOCAL INFILE 'C:/Users/User/Documents/health/owid-covid-data.csv'
 INTO TABLE covid
 FIELDS TERMINATED BY ','
 ENCLOSED BY '"'
 LINES TERMINATED BY '\n'
 IGNORE 1 LINES;

select * from  covid; 